### ISSUE TITLE
Error plotting empty Vector{Any}

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1078]
```
using Plots
pyplot()
plot([],[])
```
produces the error
`BoundsError: attempt to access 0-element Array{Any,1} at index [1]`
There is no error with
`plot(Float64[],Float64[])`
which correctly produces an empty plot.

Tested on Julia 6.0.1, Plots.jl 0.12.3, Anaconda 4.3.1.

Note that an empty Vector{Any} may sometimes be produced by code that usually produces typed vectors, when given empty input (e.g. map, vcat...).

**Comment by daschw** [comment]
Thanks for this hint! I think we could discuss, whether `plot([], [])` should return (1) an empty plot or (2) a plot with an empty series (current behaviour of `plot(Float64[],Float64[])`). I think (2) generally makes more sense, but for the use case you described (1) would probably be preferable because it would not add a legend entry for every "empty" plot call.

**Comment by yha** [comment]
I think option (2) is better. It is more consistent, and makes it clearer that the data is empty rather than not plotted. Perhaps (1) may be better for "publication-grade" figures, but this situation is more likely to occur when exploring results, and I imagine published figures are commonly more heavily configured anyway, so manually removing legend entries is not a big deal.
