### ISSUE TITLE
ERROR: No user recipe defined for DateTime

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1283]
When using a heatmap:
```julia
z = rand(5, 5)
x = DateTime(2001):Dates.Year(1):DateTime(2005)
y = 1:5
heatmap(x, y, z)
```

**Comment by wkearn** [comment]
This happens because the `SliceIt` recipe uses `convertToAnyVector` which, as of b9dea42 is commented out for DateTimes. Uncommenting https://github.com/JuliaPlots/Plots.jl/blob/df63530b89dad732aeaeee1f29f32c409e5ef623/src/series.jl#L49 fixes the heatmap for me.

I'm running into other problems with DateTime plotting right now that is preventing me from figuring out whether that change breaks the rest of the API.

**Comment by yakir12** [comment]
I just looked at the tests, I guess we need more tests or something? There's no coverage report either. Well, this specific issue is not life threatening. Thanks for looking at it!

**Comment by mkborregaard** [comment]
Test PRs are indeed welcome - they should be made to Plots/src/examples.jl

**Comment by yakir12** [comment]
Cool!

**Comment by daschw** [comment]
@wkearn uncommenting that line should be fine. Feel like making a PR?

**Comment by daschw** [comment]
The fix did not actually work.
