### ISSUE TITLE
Recipes don't support type annotations on keyword arguments

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1292]
MWE
```julia
julia> @userplot Test
test! (generic function with 1 method)

julia> f(t::Test; var::Int = 10) = randn(10)
f (generic function with 1 method)

julia> @recipe f(t::Test; var::Int = 10) = randn(10)

julia> test()
ERROR: MethodError: Cannot `convert` an object of type Expr to an object of type Symbol
This may have arisen from a call to the constructor Symbol(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] get!(::Function, ::Dict{Symbol,Any}, ::Expr) at ./dict.jl:436
 [2] apply_recipe(::Dict{Symbol,Any}, ::Test) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:284
 [3] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Test}) at /Users/michael/.julia/v0.6/Plots/src/pipeline.jl:81
 [4] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Test}) at /Users/michael/.julia/v0.6/Plots/src/plot.jl:177
 [5] #test#5(::Array{Any,1}, ::Function) at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
 [6] test() at /Users/michael/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
```

**Comment by wkearn** [comment]
@mkborregaard I know how to fix the error (there is a quick change in RecipesBase that I will open a Pull Request for).

A question is whether we should just throw away the information in the type annotation or make sure that values passed to that keyword have the right type. This will take a little bit of work to get a useful error thrown in the right place.

**Comment by mkborregaard** [comment]
That's great! Although I think the quick-fix is alright at the moment, in 0.7 I believe it is planned to have methods dispatch on the type of keyword arguments - in which case throwing away the type annotation could lead to some hard-to-track bugs.

**Comment by wkearn** [comment]
My immediate (and possibly mistaken) impression is that dispatch on keyword argument types won't be a problem for this as Plots is currently implemented. `plot` immediately wraps the keyword arguments up into a `Dict{Symbol,Any}` and then passes that around, so it forgets about the types, and nothing gets dispatched on the types of the keywords passed to `plot`.

My hacky way to enforce the type would be to add a check in the recipe macro so that an error is thrown if `get!(plotattributes, sym, val)` returns a value that isn't the type specified in the annotation.

**Comment by mkborregaard** [comment]
You know what, I think you're right. I think if we could just add a warning to the PR that the type annotations have been dropped it's good to merge, then :-) I think it's misleading to allow type annotations for keywords in the future if we aren't going to dispatch on them anyway.

**Comment by wkearn** [comment]
The error referenced in this issue is fixed now. 

While Plots won't currently do anything with the keyword argument type annotations, it seems like Makie might use named tuples for some of this (https://github.com/JuliaPlots/Makie.jl/issues/8#issuecomment-354809617), which would enable typed keyword arguments. In any case, I don't think it's worth incorporating into Plots, because it will involve redoing a lot of the argument processing pipeline. We can revisit down the road as we see how Makie shapes up. For now, I'll close this issue, though.
