### ISSUE TITLE
nbconvert --latex can not handle Plots plots

### ISSUE THREAD

**Issue by massemanet** [JuliaPlots/Plots.jl#1365]
When converting to tex, nbconvert does not undertand this construct (in the .ipynb file)
```
   "outputs": [
    {
     "data": {
      "text/html": [
       "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANh...EUgAAlNuQmCC\" />"
```

Hence, one gets
```
$ jupyter nbconvert --to latex foo.ipynb
[NbConvertApp] Converting notebook foo.ipynb to latex
/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/nbconvert/filters/datatypefilter.py:41:
UserWarning: Your element with mimetype(s) [u'text/html'] is not able to be represented.
  mimetypes=output.keys())
[NbConvertApp] Writing 15455 bytes to foo.tex
```
and the image is dropped.

Seemingly the mime type magic happens here;
https://github.com/JuliaPlots/Plots.jl/blob/master/src/output.jl#L177

Related; jupyter/nbconvert/issues/740.
ipynb example; https://github.com/jupyter/nbconvert/files/1642959/bla.ipynb.txt

**Comment by daschw** [comment]
I'm not really familiar with IJulia/Jupyter so I'm not sure how to fix this, but maybe `set_ijulia_output("image/png")` and/or `plot(..., format = :png)` could help. I have not tested this though. Hopefully someone else can provide more information.

**Comment by massemanet** [comment]
calling ```set_ijulia_output("image/png")``` in the notebook made Jupyter print nothing :<

**Comment by jleugeri** [comment]
I have the same problem, also when using a library that outputs to SVG.

In the notebook, the cell:
```julia
using Plots
pgfplots()
p=plot([1,2,3], [4,3,2])
print(typeof(p))
p
```
tells me `p` is of type `Plots.Plot{Plots.PGFPlotsBackend}`

The generated output in the `.ipynb` looks as follows:

```xml
...
   "outputs": [
    {
     "data": {
      "text/html": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=...
...
```
The figure shows correctly in the notebook, but `nbconvert` fails to convert this correctly to pdf or latex with the exact same warning `UserWarning: Your element with mimetype(s) dict_keys(['text/html']) is not able to be represented.`

In the generated PDF (or latex), the figure is just missing, as it seems the encapsulating "text/html" block just got skipped.

**However**, when using the standalone *package* `PGFPlots` instead of the backend, the following happens:

```julia
using PGFPlots
p=plot([1,2,3], [4,3,2])
print(typeof(p))
p
```
now tells me that `p` is of type `TikzPictures.TikzPicture` and the corresponding output generated in the `.ipynb` looks as follows:

```xml
   "outputs": [
    {
     "data": {
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
       "<svg xmlns=..."
       ...
      ],
      "text/plain": [
       "TikzPictures.TikzPicture(\"\\\\begin{axis}\\\\addplot+ coordinates {\\n(1, 4)\\n(2, 3)\\n(3, 2)\\n};\\n\\\\end{axis}\\n\", \"\", \"\\\\usepackage{pgfplots}\\n\\\\pgfplotsset{compat=newest}\\n\\\\pgfplotsset{every axis legend/.append style={%\\ncells={anchor=west}}\\n}\\n\\\\usepgfplotslibrary{polar}\\n\\\\usetikzlibrary{arrows}\\n\\\\tikzset{>=stealth'}\\n\", true, true)"
      ]
     },
...
```

In the notebook, this also shows correctly (albeit the figure looking a bit different due to different default settings vs `Plots.jl`, I guess), but this **also** correctly renders in the PDF generated by `nbconvert`.

tl;dr: 
creating output with mime type "text/html" leads to the output being ignored by `nbconvert`, whereas mime type "image/svg+xml" appears to work. I'd guess the same applies to e.g. "image/png" and other formats, but this is just a guess.

Would it be possible to fix the mime type of the outputs generated by `Plots.jl`? Right now they seem to default to the too general "text/html" that `nbconvert` can (understandibly) not handle.
I'd really like to use notebooks to generate PDF reports with figures, and having to `savefig` every figure to PDF and then including it via markdown (`![](image.pdf)`) is a royal PITA.

**Comment by massemanet** [comment]
@jleugerl could you try https://github.com/JuliaPlots/Plots.jl/pull/1399

**Comment by jleugeri** [comment]
Nice, looks good!
I tried a couple of combinations of `gr()`/`pyplot()`/`pgfplot()` backends, exporting to PDF/HTML with `nbconvert` for `html_output_format=:svg`/`html_output_format=:png` and it all came out fine. I think that fixed it for me!

**Comment by massemanet** [comment]
fixed in https://github.com/JuliaPlots/Plots.jl/pull/1399.
This issue can be closed if/when that is merged.
