### ISSUE TITLE
Bad hover tooltip when using dates with PlotlyJS

### ISSUE THREAD

**Issue by cstjean** [JuliaPlots/Plots.jl#1385]
The x-axis tooltip in this example is a number instead of a date.

![screenshot from 2018-02-07 08-47-39](https://user-images.githubusercontent.com/8622776/35919787-175640d2-0be4-11e8-889c-6db4832b7eff.png)

Interestingly, the tooltip works correctly when hovering over datapoints that are exactly over tick marks. The equivalent code works fine when using PlotlyJS directly. I assume that it's the same underlying issue as #1382, and probably #726

**Comment by pearlzli** [comment]
I'd also be interested in a fix to this. Does anyone have any ideas for how to get around this? I'd be happy to take a look at it, but I don't quite know where to begin.

**Comment by mkborregaard** [comment]
Maybe the solution is when the DateTimeFormatter runs to create the date breaks on the x axis to check if `hover` is set explicitly, and if it isn't set it explicitly with formatted dates.

**Comment by pearlzli** [comment]
I'll try that, thanks!

As an aside, I noticed that `datetimeformatter`, `dateformatter`, and `timeformatter` are not listed in the [attributes table](http://docs.juliaplots.org/latest/attributes/). I can add that via pull request if you want, but which file should I edit to do so?

**Comment by pearlzli** [comment]
@cstjean Yes, I just noticed this - thanks for implementing that! However, I also want to do two more things: set my own tick-marks and show my dates as quarters (e.g. "2010-Q1" instead of "Mar 2010"). I'm trying to implement that now using the `formatter` attribute...

@mkborregaard Upon further investigation, I think the `hover` attribute changes the string that's displayed next to the actual data value (currently "15" in @cstjean's example), not the string displayed on the x-axis.

**Comment by mkborregaard** [comment]
That's right, sorry. I

**Comment by johnrichardrinehart** [comment]
@pearlzli I think this issue should be closed in light of `ticks=:native` solving this particular problem.
