### ISSUE TITLE
PGFPlots backend produces extra braces in .tex output leading to compile failures

### ISSUE THREAD

**Issue by abhinavd** [JuliaPlots/Plots.jl#1396]
Here's a minimal example:
```
using Plots
pgfplots()  
using LaTeXStrings  
plt = plot()  
xticks!([0.1,0.2],[L"\alpha", L"\beta"])  
savefig(plt, "minimal_bug.tex")  
```
gives an error upon running the fifth line. If I change `L"\alpha"` and `L"\beta"` to `L"a"` and `L"b"` it works fine.
Upon examining the .tex output I see the following:
```
\begin{tikzpicture}[]
\begin{axis}[height = {101.6mm}, ylabel = {}, xmin = {0.0}, xmax = {1.0}, ymax = {1.0}, xlabel = {}, {unbounded coords=jump, scaled x ticks = false, xticklabel style={rotate = 0}, xmajorgrids = true, xtick = {0.1,0.2}, xticklabels = {$\alpha$,$\beta$}, xtick align = inside, axis lines* = left, scaled y ticks = false, yticklabel style={rotate = 0}, ymajorgrids = true, ytick = {0.0,0.2,0.4,0.6000000000000001,0.8,1.0}, yticklabels = {0.0,0.2,0.4,0.6,0.8,1.0}, ytick align = inside, axis lines* = left,     xshift = 0.0mm,
    yshift = 0.0mm,
    axis background/.style={fill={rgb,1:red,1.00000000;green,1.00000000;blue,1.00000000}}
}, ymin = {0.0}, width = {226.822mm}]\end{axis}

\end{tikzpicture}
```
In the above, there is an extra pair of braces from `{unbounded coords = jump` to `1.00000000}}
}` which causes the above error. Removing this set of braces gives a .tex file that compiles properly.
I suspect the problem is in the usage of one of the `push!` methods in the pgf backend [file](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pgfplots.jl).

**Comment by apalugniok** [comment]
I think it's because the `style` here https://github.com/JuliaPlots/Plots.jl/blob/a4636fd88d271ceeb99d00d7edf214b888e5d177/src/backends/pgfplots.jl#L375 is defined as an array of strings which causes it to get wrapped in `{}` by PGFPlots when it is passed into the Axis constructor here https://github.com/JuliaPlots/Plots.jl/blob/a4636fd88d271ceeb99d00d7edf214b888e5d177/src/backends/pgfplots.jl#L453

I got the same error from your example when I passed `["xtick = {0.1,0.2}", "xticklabels = {\$\\alpha\$,\$\\beta\$}"]` to `style` in PGFPlots.jl.

Using `join{style, ",")` seems to fix the issue, I'll check it more thoroughly tomorrow. Good spot on the brackets 😄!

**Comment by abhinavd** [comment]
Great, thanks! I tried it and it works.
