### ISSUE TITLE
Horizontal bars broken on Plotly.

### ISSUE THREAD

**Issue by apalugniok** [JuliaPlots/Plots.jl#1410]
```
using Plots; plotly()
xs = [ "x$i" for i in 1:10 ]
p = bar(xs, -5:4, orientation = :h)
```
![newplot](https://user-images.githubusercontent.com/22132297/36631095-c79bd122-1969-11e8-9715-0b4498616caa.png)
```
julia> p[1][1][:x]
10-element Array{String,1}:
 "x1" 
 "x2" 
 "x3" 
 "x4" 
 "x5" 
 "x6" 
 "x7" 
 "x8" 
 "x9" 
 "x10"

julia> p[1][1][:y]
10-element Array{Float64,1}:
 0.5
 1.5
 2.5
 3.5
 4.5
 5.5
 6.5
 7.5
 8.5
 9.5
```
There is also a disagreement with `axis[:discrete_values]`
```
julia> p[1][:yaxis][:discrete_values]
10-element Array{Any,1}:
 "x1" 
 "x2" 
 "x3" 
 "x4" 
 "x5" 
 "x6" 
 "x7" 
 "x8" 
 "x9" 
 "x10"

julia> p[1][:xaxis][:discrete_values]
0-element Array{Any,1}
```
which is making `ticks = :native` output both x and y as the array `["x1", "x2", ... , "x10"] and gives 
![newplot 1](https://user-images.githubusercontent.com/22132297/36631285-227db526-196d-11e8-8f9e-2ecc8b339705.png)

**Comment by wkearn** [comment]
This was a fun one. It happens in [here](
https://github.com/JuliaPlots/Plots.jl/blob/dbe5b7830738d1b8f745ad98b701dec01c8d6fb6/src/axes.jl#L319-L348) because the x-axis does not get properly updated when the orientation is horizontal. It affects Plotly/PlotlyJS because they rely on native support for `:bar` whereas the others (GR, PyPlot, and PGFPlots, at least) use the `step` recipe.

A fix is on the way!
