### ISSUE TITLE
seriescolor in recipe is ignored 

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1520]
@mkborregaard found out that the following doesn't plot in red (this is from my question on [Discourse](https://discourse.julialang.org/t/consistent-plotting-attributes/10822?u=yakir12)):
```julia
@recipe function f(::Type{Val{:home}}, x,y,z)
       seriescolor := :red
       markershape := :star5
       seriestype := :scatter
       x,y
  end

plot(rand(5), st = :home)
```

**Comment by mkborregaard** [comment]
I also tried the more specific `markercolor`, which fails with error message:
```
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: MethodError: no method matching alpha(::Symbol)
Closest candidates are:
  alpha(::ColorTypes.AGray32) at /Users/michael/.julia/v0.6/ColorTypes/src/traits.jl:11
  alpha(::ColorTypes.ARGB32) at /Users/michael/.julia/v0.6/ColorTypes/src/traits.jl:10
  alpha(::ColorTypes.RGB24) at /Users/michael/.julia/v0.6/ColorTypes/src/traits.jl:9
  ...
```

**Comment by daschw** [comment]
The issue is the order in the pipeline in https://github.com/JuliaPlots/Plots.jl/blob/master/src/plot.jl#L219-L236: At first the defaults are applied including matching `:auto` linecolors etc. with the corresponding seriescolors. Then the seriesrecipe is applied. If this changes e.g. the seriescolor, linecolor still holds the default seriescolor from before.
We could try reversing the order, but it might not be that straightforward and I'm not sure if this could cause other issues.
Otherwise, series recipes really should specify the most specific argument.
@mkborregaard's example from above should be fixed by https://github.com/JuliaPlots/Plots.jl/pull/1522
However, there's still an issue, for instance, with
```julia
gr()
@recipe function f(::Type{Val{:test}}, x,y,z)
       markercolor := 3
       seriestype := :scatter
       x,y,z
end
plot(1:5, st = :test)
```
`markercolor = 3` would be replaced by the 3rd color of the default palette in `_add_defaults!`, which is however called before the series recipe is processed. Hence gr.jl and finally `alpha(c)` gets `markercolor = 3`, which it cannot handle:
```julia
plot(1:5, st = :test)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: MethodError: no method matching plot_color(::Int64)
Closest candidates are:
  plot_color(::Any, ::Void) at /home/dani/.julia/v0.6/PlotUtils/src/colors.jl:15
  plot_color(::Any, ::Number) at /home/dani/.julia/v0.6/PlotUtils/src/colors.jl:18
  plot_color(::Symbol) at /home/dani/.julia/v0.6/PlotUtils/src/colors.jl:6
  ...
```
We could go along and fix this and similar future issues with separate fix in the way of https://github.com/JuliaPlots/Plots.jl/pull/1522, but getting the order right might be the more sustainable solution.

**Comment by mkborregaard** [comment]
Wow, great work @daschw :-O :tada:

**Comment by yakir12** [comment]
Like assigning "specificity" values to attributes and sorting by that?

**Comment by yakir12** [comment]
After (my) last update it now works! So I'm closing this :smile:

**Comment by daschw** [comment]
Oh, thanks, yes #1523 should have fixed it 🙂
