### ISSUE TITLE
Error when putting "using Plots"

### ISSUE THREAD

**Issue by ayaka-usui** [JuliaPlots/Plots.jl#1613]
I have a problem. I would like to plot, and I think that a simple way is to use a package "Plots". I have installed Plots by putting 'Pkg.add("Plots")'. Then, "using Plots; plot(x,y)" is supposed to work, I think. But a lot of errors came out. It would be great if you tell me what is going on.

```
julia> using Plots
INFO: Precompiling module Plots.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiledcache file for module Dates. Got:
WARNING: Cache file "/Users/usui/.julia/lib/v0.6/Dates.ji" not found.
WARNING: eval from module Main to Plots:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/usui/.julia/v0.6/Dates/src/Dates.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: requiring "Dates" in module "Plots" did not define a corresponding module.
ERROR: LoadError: ArgumentError: Module Printf not found in current path.
Run `Pkg.add("Printf")` to install the Printf package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /Users/usui/.julia/v0.6/Plots/src/Plots.jl, in expressionstarting on line 9
ERROR: Failed to precompile Plots to /Users/usui/.julia/lib/v0.6/Plots.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] macro expansion at /Users/usui/.julia/v0.6/Atom/src/repl.jl:118 [inlined]
 [5] anonymous at ./<missing>:?
```

**Comment by daschw** [comment]
What does `Pkg.status("Plots")` say?

**Comment by ayaka-usui** [comment]
Thanks for the quick response! It says:
```
julia> Pkg.status("Plots")
 - Plots                         0.17.3+            master
```

**Comment by daschw** [comment]
Master is julia 0.7 only. 0.17.4 is the last version to support julia 0.6. You have to do `Pkg.free("Plots")` (and maybe `Pkg.update()`) in order to use Plots.

**Comment by ayaka-usui** [comment]
I did `Pkg.free("Plots")` and `Pkg.update()`. In putting `using Plots`, there are still errors but they are different from those of before. But `plot(x,y)` works. Thanks! These are their results:

```
julia> Pkg.free("Plots")
INFO: Freeing Plots
INFO: No packages to install, update or remove

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Cloning cache of FunctionalCollections from https://github.com/JuliaCollections/FunctionalCollections.jl.git
INFO: Cloning cache of JSExpr from https://github.com/JuliaGizmos/JSExpr.jl.git
INFO: Cloning cache of Observables from https://github.com/JuliaGizmos/Observables.jl.git
INFO: Cloning cache of WebIO from https://github.com/JuliaGizmos/WebIO.jl.git
INFO: Upgrading Blink: v0.6.2 => v0.7.0
INFO: Installing FunctionalCollectionsv0.3.2
INFO: Installing JSExpr v0.2.0
INFO: Installing Observables v0.1.2
INFO: Installing WebIO v0.2.4
INFO: Building HttpParser
INFO: Building MbedTLS
Info: using prebuilt binaries
INFO: Building WebIO
INFO: Building Blink

julia> using Plots
INFO: Precompiling module Plots.
WARNING: using Plots.savefig in moduleMain conflicts with an existing identifier.
WARNING: using Plots.quiver in module Main conflicts with an existing identifier.
WARNING: using Plots.twinx in module Main conflicts with an existing identifier.
WARNING: using Plots.hexbin in module Main conflicts with an existing identifier.
WARNING: using Plots.barh in module Main conflicts with an existing identifier.
WARNING: using Plots.bar in module Main conflicts with an existing identifier.
WARNING: using Plots.scatter in moduleMain conflicts with an existing identifier.
WARNING: using Plots.pie in module Main conflicts with an existing identifier.
WARNING: using Plots.arrow in module Main conflicts with an existing identifier.
WARNING: using Plots.text in module Main conflicts with an existing identifier.
WARNING: using Plots.contourf in module Main conflicts with an existing identifier.
WARNING: using Plots.spy in module Main conflicts with an existing identifier.
WARNING: using Plots.grid in module Main conflicts with an existing identifier.
WARNING: using Plots.plot in module Main conflicts with an existing identifier.
WARNING: using Plots.contour in moduleMain conflicts with an existing identifier.
WARNING: using Plots.boxplot in moduleMain conflicts with an existing identifier.

```
One more thing I want to ask is how to remove the errors after `using Plot`, though `plot` works. For you information, as you mentioned, the version of julia in mine is 0.6:

```
julia> VERSION
v"0.6.4"
```

**Comment by daschw** [comment]
Are these warnings still appearing if you restart julia and run `using Plots`?

**Comment by ayaka-usui** [comment]
You are right! No error arose after julia restarted. Thanks a lot, daschw!

```
Press Enter to start Julia.
Starting Julia...
INFO: Loading HttpServer methods...
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Plots

julia> plot(rand(100))

julia>
```

**Comment by daschw** [comment]
No, problem, I'm glad it works now!

**Comment by ABMSUH** [comment]
Hi,
I am facing big problem in Julia as follow:

“We tried to lunch Julia from:
C:\Users\Pechman\AppData\Local\Julia-1.1.0\bin\julia.exe
This path can be changed in the settings.
Details:
Access is denied.”

Please advise me to fix it…

**Comment by Apmazzini** [comment]
I have an error when I'm plotting too, have you been through this?



julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Deps path: C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\src\..\deps\deps.jl
ERROR: LoadError: FFMPEG not installed properly, run `] build FFMPEG`, restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\src\FFMPEG.jl:18
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:432
 [9] top-level scope at .\none:3
in expression starting at C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\src\FFMPEG.jl:16
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\Des
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:432
 [12] top-level scope at .\none:3
in expression starting at C:\Users\Desktop\.julia\packages\Plots\h3o4c\src\Plots.jl:11
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\Desktop\.julia\compiled\v1.2\Plots\ld3vC.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [2] _require(::Base.PkgId) at .\loading.jl:1013
 [3] require(::Base.PkgId) at .\loading.jl:911
 [4] require(::Module, ::Symbol) at .\loading.jl:906

(v1.2) pkg>  build FFMPEG
  Building FFMPEG → `C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\deps\build.log`
┌ Error: Error building `FFMPEG`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:797
│ ┌ Error: Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - A fun��o de revoga��o n�o p�de verificar a revoga��o do certificado.
│ └ @ Base download.jl:43
│ ERROR: LoadError: failed process: Process(`'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\deps\build_Bzip2.v1.0.6.jl' https://github.com/JuliaPackaging/Yggdrasil/releases/download/Bzip2-v1.0.6-2/build_Bzip2.v1.0.6.jl`, ProcessExited(35)) [35]
│ 
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:813 [inlined]
│  [2] download_curl(::String, ::String, ::String) at .\download.jl:44
│  [3] download(::String, ::String) at .\download.jl:52
│  [4] top-level scope at C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\deps\build.jl:46
│  [5] include at .\boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1094
│  [7] include(::Module, ::String) at .\Base.jl:31
│  [8] include(::String) at .\client.jl:431
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\Desktop\.julia\packages\FFMPEG\9JQpZ\deps\build.jl:44
│ caused by [exception 1]
│ IOError: symlink: operation not permitted (EPERM)
│ Stacktrace:
│  [1] uv_error at .\libuv.jl:90 [inlined]
│  [2] symlink(::String, ::String) at .\file.jl:800
│  [3] probe_symlink_creation(::String) at C:\Users\Desktop\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:121
│  [4] #probe_platform_engines!#30(::Bool, ::typeof(BinaryProvider.probe_platform_engines!)) at C:\Users\Desktop\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:175
│  [5] probe_platform_engines! at C:\Users\Desktop\.julia\packages\BinaryProvider\TcAwt\src\PlatformEngines.jl:169 [inlined]
│  [6] __init__() at C:\Users\Desktop\.julia\packages\BinaryProvider\TcAwt\src\BinaryProvider.jl:28
│  [7] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:685
│  [8] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:765
│  [9] _require(::Base.PkgId) at .\loading.jl:990
│  [10] require(::Base.PkgId) at .\loading.jl:911
│  [11] require(::Module, ::Symbol) at .\loading.jl:906
│  [12] include at .\boot.jl:328 [inlined]
│  [13] include_relative(::Module, ::String) at .\loading.jl:1094
│  [14] include(::Module, ::String) at .\Base.jl:31
│  [15] include(::String) at .\client.jl:431
│  [16] top-level scope at none:5
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
