### ISSUE TITLE
@df macro giving issues in 0.7 rc2

### ISSUE THREAD

**Issue by vishaluk** [JuliaPlots/Plots.jl#1632]
I installed Julia 0.7 rc2 and added Packages - StatPlots, DataFrames. A very simple code like the following is giving me error. 

using DataFrames, StatPlots
gr(size=(400,300))
test = DataFrame(a = 1:5, b = 11:15 )
@df test plot(:a, :b)

results in -
UndefVarError: column_names not defined

Stacktrace:
 [1] extract_columns_from_iterabletable(::DataFrame) at /Users/vishalsharma/.julia/packages/StatPlots/z792K/src/df.jl:145
 [2] (::getfield(Main, Symbol("##5#6")))(::DataFrame) at ./none:0
 [3] top-level scope at none:0

**Comment by mkborregaard** [comment]
Could you open this in StatPlots instead and ping @piever ?

**Comment by piever** [comment]
StatPlots was not yet updated for 0.7, I'm surprised it even loads :)

Somehow TableTraits deleted the `column_names` function, but it should be easy to fix. There may be more issues with `@df` due to `QuoteNode` changes in Julia Base.

Also, be careful with quoting code as you accidentally pinged user Dan Freeman.
