### ISSUE TITLE
another 0.7 / 1.0 thing

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#1641]
I use plots with Plotly().  This warning arises:

```
┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::PlotUtils.ColorGradient` with `Ref(x)` to ensure they broadcast as "scalar" elements.
│   caller = ip:0x0
└ @ Core :-1
```

It is triggered by this call:
```
    pyplot()
    clibrary(:misc)  # collection of color palettes
    img = reshape(digit_data, digit_dims...)'
    pldigit = plot(img, seriestype=:heatmap, color=:grays,  
        showaxis=false, legend=false, yflip=true, size=(400,400)) # right_margin=6mm, bottom_margin=6mm
    display(pldigit)
```
clibrary is a holdover from PlotlyJS.  It has lots of problems--maybe a long time till we see it again.
I tried wrapping the color named argument with Ref() but that did nothing.  So, I think the warning must from from within Plots.  Perhaps?

**Comment by mkborregaard** [comment]
The problem here is the broadcast here https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L1566-L1582  , introduced in https://github.com/JuliaPlots/Plots.jl/commit/f89b1ba303fd4f40a392a023f3e3fcb3a05181c0 
Under 0.7/1.0 , the ColorGradient will not work in the broadcast unless wrapped by a Ref, but a ColorGradient is only sometimes passed.

BTW `clibrary` is not a holdover from PlotlyJS, it's defined in PlotUtils. What problems does it have?

**Comment by lewisl** [comment]
No problem with clibrary.  I didn’t realize it was used across multiple backends.  My mistake.

**Comment by lewisl** [comment]
I tried wrapping the arguments I pass, but that does nothing because the arguments are just symbols.  Somewhere in Plots the call that needs to be wrapped is made.

**Comment by mkborregaard** [comment]
Just updaet - I already made a PR to solve this issue, merged and tagged a new release.
