### ISSUE TITLE
Why did PGFPlots adapter get so buggy starting in January?

### ISSUE THREAD

**Issue by djsegal** [JuliaPlots/Plots.jl#1677]
At some point since January, the PGFPlots portion of Plots.jl has gotten extremely buggy.

+ Surfaces with `fill` break often
+ Using `NaN` in arrays usually has no effect
+ Font-sizes are hardcoded into figures (and not easily editable in LaTeX documents)

How did all these things happen? Were they done to make other backends easier? 

Just trying to understand the problem before I roll up my sleeves and help with the effort

**Comment by djsegal** [comment]
A little vague. Not really helpful. I'll try to turn these into separate issues in the future.

Closing

**Comment by mkborregaard** [comment]
It's true that it is vague and separate issues will be more helpful, but it's an important observation - the pgfplots backend is important for Plots and we must make sure it's not left by the wayside. Any help is much appreciated!

Looking into the commit history reveals no noticeable trend since january, but one weakness of Plots' testing system is that most tests are only run using the GR backend, because there's been some issues getting the other backends to work well on Travis. Expanding testing to the other backends too would be nice though.
