### ISSUE TITLE
Multiple rows in xlabel and ylabel

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaPlots/Plots.jl#1846]

**Comment by Kelvyn88** [comment]
Hi,

How do I create a xlabel or y label with 2 rows? I just tried with [L"row1",L"row2" ] (note that I am using LaTeXStrings).

Thanks

**Comment by daschw** [comment]
Without LaTeXStrings you could do `xlabel = "row1\nrow2")`, but I have no idea how to achieve this with LaTeXStrings.

**Comment by lnacquaroli** [comment]
Sorry for being too late. 
You could use `latexstring` instead of `L` with `LaTeXStrings` (https://github.com/stevengj/LaTeXStrings.jl). For instance,

```julia
using Plots; pyplot()
using LaTeXStrings
plot(cumsum(randn(100))
xlabel!(latexstring("This is the \n \$\\mu\$-axis"))
ylabel!(latexstring("This is the \n \$\\int_0^\\inf dx\$-axis"))
```


gives:


![figure_1](https://user-images.githubusercontent.com/26485264/50499425-8c8bab80-0a17-11e9-85de-e56a3865ccce.png)



You just need to remember to escape `$` and any command starting with `\`.

**Comment by Kelvyn88** [comment]
Thanks!!! It is the code that I was looking for.

**Comment by Bebotron** [comment]
This solution does not work using `gr()`. Any help on how to do it on that backend?
