### ISSUE TITLE
linealpha with Shape modifies colorbar

### ISSUE THREAD

**Issue by andferrari** [JuliaPlots/Plots.jl#1976]
Trying to remove lines around `Shape()` I have noticed that `linealpha` acts on the colorbar:
`plot(Shape(rand(3), rand(3)), fill_z=1, linealpha=0.1)`

**Comment by tamasgal** [comment]
The same is true for the `alpha` parameter.

Moreover, there seems to be a saved state, since the value of `alpha` is persistent on sub sequential calls of `plot`:

![Screenshot 2019-03-31 at 22 37 15](https://user-images.githubusercontent.com/1730350/55294704-8dacea00-5405-11e9-9c6f-17b0c82200e7.png)
