### ISSUE TITLE
Superscript '^' and subscript '_' don't work with gr() backend

### ISSUE THREAD

**Issue by damonturney** [JuliaPlots/Plots.jl#2006]
using Plots
gr()
plot(1,xlabel="hi^2")

doesn't produce a superscript.

And since latex doesn't work with gr() backend, see issue here https://github.com/JuliaPlots/Plots.jl/issues/2005, there is NO way to produce superscripts or subscripts with the gr() backend.

**Comment by daschw** [comment]
> doesn't produce a superscript.

It's not supposed to. You can use unicode symbols like ², or LaTeXStrings, which should work. I'm not sure why it does not for you.

Also, I recommend using ` or ``` around code in github issues. This makes it easier to read for others.

**Comment by briochemc** [comment]
> You can use unicode symbols like ², or LaTeXStrings, which should work.

Not all Unicode symbols work though. For example:
```julia
using Plots
scatter(rand(10), rand(10), xlabel="Digits superscripts (⁻¹²³⁴⁵⁶⁷⁸⁹⁰)")
```
produces (Julia v1.1.1, OSX v10.13.6, Plots v0.25.3, GR v0.41.0)
![Screen Shot 2019-08-12 at 12 23 25 PM](https://user-images.githubusercontent.com/4486578/62843275-08fba200-bcfc-11e9-851c-df744e6ed326.png)

Additionally, while LaTeXStrings provides a solution, IMHO it is not a good one because (i) it produces a different and serif font, and (ii), it doesn't allow to easily mix math and non-math mode AFAIU.

I think it is important for scientific plots to allow for a few superscripts and subscripts (mainly for units, thus the `⁻¹²³⁴⁵⁶⁷⁸⁹⁰` of my MWE above, and probably some straight-up greek letters like `μ`).

For that reason I tend to end up using the PyPlot backend more than the other options:
```julia
pyplot()
scatter(rand(10), rand(10), xlabel="Digits superscripts (⁻¹²³⁴⁵⁶⁷⁸⁹⁰)") 
```
which produces (PyCall v1.91.2, PyPlot v2.8.1)
![Screen Shot 2019-08-12 at 12 27 39 PM](https://user-images.githubusercontent.com/4486578/62843367-b4a4f200-bcfc-11e9-929b-8c123a8de998.png)

But anyway, this is probably more a GR.jl issue than a Plots.jl one though, right?

**Comment by JackDevine** [comment]
Indeed this is a GR issue, I don't think that there is anything that can be done here on the Plots side.

**Comment by mzechmeister** [comment]
Sub- and superscripts works at least when using `10` as base and curly brackets
```
plot(1, xlabel="10^{-0123456789abc}_{-0123456789abc}")
```
![grafik](https://github.com/JuliaPlots/Plots.jl/assets/32583239/5b333a53-96c4-428c-a3dc-ad7033513f56)
