### ISSUE TITLE
annotate! in pyplot not working outside plot

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Plots.jl#2097]
Hi, 
does anyone knows why or how to force the pyplot backend to put an annotation outside the plot. At the moment it's not working. 
`using Plots`
`pyplot()`
`x = LinRange(0.0,2π, 100)`
`plot(x, sin.(x), size = (350, 200))`
`annotate!(-0.9, 1, text("(a)", 12, :red))`

with the gr backend works fine!

`using Plots`
`gr()`
`x = LinRange(0.0,2π, 100)`
`plot(x, sin.(x), size = (350, 200))`
`annotate!(-0.9, 1, text("(a)", 12, :black))`

I'm using `Julia-1.0.3`,  `Plots v0.25.1`, `PyPlot v2.8.1` and `GR v0.40.0`

**Comment by jacobcook1995** [comment]
From the matplotlib documentation (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.annotate.html) it seems like this behaviour is controlled by annotation_clip, which is a bool that defaults to true if not provided. true here means that annotations falling outside plot area are not added to the figure. It seems like when the annotate function is defined in the PyPlot backend (at I think lines 1229 to 1247 of Plots.jl/pyplot.jl) annotation_clip isn't set meaning that it defaults to true.

I've been trying to think of a way to force Plots.jl's annotate function to have a different value for annotation_clip but I'm not sure if my knowledge of Julia is sufficient.

**Comment by jacobcook1995** [comment]
Can get the desired behaviour using PyPlot

`using PyPlot

x = collect(0.0:0.1:10.0)
y = collect(0.0:0.1:10.0)
plot(x,y)
annotate("A",xy=[-2.0;10.0],annotation_clip=false)`

This gives an annotation outside the plotting area as desired

![test2](https://user-images.githubusercontent.com/32497818/63863718-9569be00-c9a6-11e9-89d4-dfba53d1a540.png)

So I guess the issue lies at the level of Plots.jl rather than PyPlot.jl.
