### ISSUE TITLE
contour interferes with 

### ISSUE THREAD

**Issue by sswatson** [JuliaPlots/Plots.jl#2229]
Contour plotting with the GR backend seems to interfere with the colors in heatmaps. Here's a MWE:

```julia
using Plots
xs = ys = -3:0.01:3
heatmap(xs, ys, (x,y) -> sign(x^2 - y^2 - 1))
```
![img1](https://user-images.githubusercontent.com/8516843/67644211-bc386800-f8f5-11e9-9f60-5e7ed96766f5.png)

```julia
using Plots
xs = ys = -3:0.01:3
heatmap(xs, ys, (x,y) -> sign(x^2 - y^2 - 1))
contour!(xs, ys, (x,y) -> x^2 - y^2 - 1, levels = [0])
```
![img2](https://user-images.githubusercontent.com/8516843/67644210-bc386800-f8f5-11e9-8066-d983afd24cd3.png)

I know that `contour` has a `fill` option, but I don't see why it should be a problem to use heatmap plus the no-fill contour.

**Comment by mkborregaard** [comment]
This  is the general issue of colorbar sharing which causes many unforeseen regressions. @daschw do you remember when this was added?

**Comment by daschw** [comment]
The issue here is that `clims` is a subplot attribute. Hence, a single subplot has to share the colorbar limits of all series.
Related changes are https://github.com/JuliaPlots/Plots.jl/commit/13111b377996961fee5e0ae2943aa7bccf6224b5 and more recently https://github.com/JuliaPlots/Plots.jl/pull/1969.

**Comment by daschw** [comment]
With #2230 you should be able to fix this by adding `colorbar_entry = false` to your `contour!` call.

**Comment by sswatson** [comment]
Looks perfect, thanks!
