### ISSUE TITLE
Zero-spaced subplot stack with backend pgfplotsx().

### ISSUE THREAD

**Issue by theomb21** [JuliaPlots/Plots.jl#2482]
Might it be possible to realize [multi-panel plots](https://github.com/JuliaPlots/Plots.jl/issues/376) within the `pgfplots()` backend?
It is [possible](https://discourse.julialang.org/t/subplots-without-gap-between-them/27491) with Package `PGFPlotsX`.

If it was possible, one could e.g. catch for the options of the `bottom_margin` (=0, maybe along with `link=:x`) and then add the group option? I'm afraid I wasn't able to figure it out how multiple subplots are assembled in the [backends source file](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pgfplotsx.jl). (happens [here](https://github.com/JuliaPlots/Plots.jl/blob/0d210843e7d853951a0abb57517af091bd7ac26e/src/backends/pgfplotsx.jl#L97) ?)

Last, thanks to all contributors and maintainers of the pgfplotsx() backend for the nice work. The PGFPlotsX package brings all the flexibility to custom design publication-ready graphics within Julia and incorporation into the versatile `Plots` saves code and gives access for the daily use by providing decent default-results.

**Comment by mkborregaard** [comment]
"all contributors and maintainers of the pgfplotsx() backend" is @BeastyBlacksmith :-D :heart:

**Comment by BeastyBlacksmith** [comment]
This is another example of "layouting is currently a mess". I take the opportunity and explain in a little more detail.

The layouting code is mostly [this section](https://github.com/JuliaPlots/Plots.jl/blob/0d210843e7d853951a0abb57517af091bd7ac26e/src/backends/pgfplotsx.jl#L145-153).
The problem is
- it takes width and height of the subplot bounding box, but should take the bounding box of the subplot plotarea
- it doesn't respect setting of margins (at the moment it is unclear to me whether this needs to be accounted for in the backend or if the frontent code already does this)
- it also does not check the `:link` keyword which would be responsible for what you ask for

Regarding the groupplots library showed in the discourse thread: I removed it on purpose, because it was incompatible with polar plots.

To answer your question: Yes, that is definitely doable, but I can't promise you any timeframe. If you wan't to take action you can always talk to me either here or on slack :).
I'm happy the backend is otherwise useful for you.

**Comment by BeastyBlacksmith** [comment]
I made a start here (https://github.com/JuliaPlots/Plots.jl/pull/2486)

**Comment by BeastyBlacksmith** [comment]
on this branch I can do the following:
```julia
julia> x = 1:10; y1 = x .* 2; y2 = x .* -0.1 .- 1;
julia> plot(x, y1, layout = (2,1), bottom_margin = -15.5Plots.mm, link = :y); scatter!(x, y2, subplot=2, top_margin = 0Plots.mm)
```
![image](https://user-images.githubusercontent.com/18145188/78604159-a7bfaa80-7859-11ea-8e7b-a3e9e5965eb7.png)

Linking of the axes is not yet implemented

**Comment by BeastyBlacksmith** [comment]
Note to myself: actually `link` does work, if one uses `link = :all`. It's just not what would be wanted, which is having only the same spacing of ticks in both subplots.
