### ISSUE TITLE
[FR] spacing between markers and text in legend

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#2631]
Please search existing issues to avoid duplicates.
Hi,
so far I am aware of there is no option to adjust the spacing between markers and text in legends. Lets say, one is restricted on specific sizes in plots. The following MWE results in:
```
plot([1,2,3],
    size=(100,200),
    marker=:circle,
    linetype=:scatter,
    legend=:outertop,
    label="some label"
)
```

![grafik](https://user-images.githubusercontent.com/12518354/80285086-63b61c00-871a-11ea-8745-f4f982cd6c46.png)

There is some space between the legend text and the marker which can be reduced to fit the legend into the figure. Should this be implemented? Should the space between text and marker depend on the linetype? Because with a non scatter linetype the legend looks like this
```
plot([1,2,3],
    size=(100,200),
    marker=:circle,
    legend=:outertop,
    label="some label",
)
```
![grafik](https://user-images.githubusercontent.com/12518354/80285254-839a0f80-871b-11ea-8797-2fbc80049b94.png)

Maybe related to https://github.com/JuliaPlots/Plots.jl/pull/2616?

**Comment by mmikhasenko** [comment]
I think the alignment of specific types of markets is dangerous because of the vertical alignment of different labels in case you have several series. Now, it is done pretty well.

![image](https://user-images.githubusercontent.com/22725744/80285497-b77a3280-8725-11ea-8291-12bd5678d8ad.png)

For your case, one solution would be to increase a bit the size.


PS:
just checked it with `gr()`.
![image](https://user-images.githubusercontent.com/22725744/80285410-05db0180-8725-11ea-87af-35f05b15d419.png)

It slightly readjusts the picture at the second evaluation (well, it does not really help)
![image](https://user-images.githubusercontent.com/22725744/80285401-f8257c00-8724-11ea-8dd7-27c01f8c03a9.png)

**Comment by BeastyBlacksmith** [comment]
I experienced that this only happens for the `outer` legendpositions with `GR`

**Comment by jamblejoe** [comment]
> I think the alignment of specific types of markets is dangerous because of the vertical alignment of different labels in case you have several series. 
I can see that this makes sense. I think we should keep this behaviour. Best is probably, to just increase size of the plot or reduce fontsize.

Maybe this can be closed then.
