### ISSUE TITLE
[FR] align legend to the left in PGFPlotsX

### ISSUE THREAD

**Issue by szcf-weiya** [JuliaPlots/Plots.jl#2712]
By default, the PGFPlotsX backend would align the content of legend in the center, such as examples in the gallery page https://docs.juliaplots.org/latest/generated/pgfplotsx/#pgfplotsx-ref11-1. In pure PGFPlotsX, I found a way to change the alignment to the left by passing the following option,
```julia
{"legend cell align" => "left"}
# or write as
{legend_cell_align = "left"}
```
but I cannot find the corresponding argument in Plots. Maybe I have missed something, but if not, hope this argument can be added.

**Comment by BeastyBlacksmith** [comment]
And you can use that via the `extra_kwargs` machinery here also
```julia
plot(fill(1:5,2), label=["a" "bbb"],
    legend_cell_align = "left",
    extra_kwargs = :subplot # let extra options count per subplot, since legend is a subplot attribute
)
```

**Comment by szcf-weiya** [comment]
Thanks for your help! I think I also need to update my Plots, since it throws that `unknown key: legend_cell_align`, but then I found that the `extra_kwargs` was recently enabled for PGFPlotsX in https://github.com/JuliaPlots/Plots.jl/pull/2200. Finally, it works well in Julia1.4.0 + Plots 1.2.2 + PGFPlotsX 1.2.6.

**Comment by isentropic** [comment]
I believe this should still be a default behavior of pgfplots though

**Comment by BeastyBlacksmith** [comment]
Fair enough

**Comment by avonmoll** [comment]
I'm still getting legend entries centered by default.

The axis option `legend cell align={left}` is indeed added (per PR #2714), but it is among the first few options. It ends up getting overridden by `legend style={...cells={anchor={center}}...}`. And this legend style is set via [this line](https://github.com/JuliaPlots/Plots.jl/blob/6df1f384927d3dc7f6e12e2380f8dd8f45c68657/src/backends/pgfplotsx.jl#L158) which calls `pgfx_get_legend_style(sp)`. The horizontal alignment for legend cells is set to `legfont.halign`, if it exists. The `legfont` comes from the `legendfont(sp)` function of Plots.jl. I found ` halign = sp[:legend_font_halign]` inside that function. So somehow the default `:legend_font_halign` is set to center (but this only happens with PGFPlotsX backend).

I confirmed that editing the TiKZ output by moving `legend cell align={left}` to the end of the `axis` options forces the legend entries to be left-aligned. Also, using `extra_kwargs` in the plot command, as suggested in the original answer, works because it places `legend cell align={left}` at the end of the option list as well.

**Comment by BeastyBlacksmith** [comment]
Honestly, the Plots default for this value is `:hcenter` since 4 years introduced in https://github.com/JuliaPlots/Plots.jl/commit/9f5be974b60ad8dccb59dbc61d434a8368f91aa7, but the pgfplotsx backend is the only backend that actually reads it.
Thus I'd suggest to put a `default(legend_font_halign=:left)` in your script or startup until we can change that in 2.0.
