### ISSUE TITLE
[BUG] GR negative exponents look ugly

### ISSUE THREAD

**Issue by isentropic** [JuliaPlots/Plots.jl#2810]
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     | x   |
plotly       |     |   x |
plotlyjs     |     |   x |
pgfplotsx    |     |  x  |
inspectdr    |     |     | x

Both
```
plot(1e-12 .* rand(100), ticks=:native)
plot(1e-12 .* rand(100))
```
produce (similar)

![image](https://user-images.githubusercontent.com/24591123/85504999-3ad1da80-b628-11ea-9746-c73f0c55208b.png)
![image](https://user-images.githubusercontent.com/24591123/85505056-62c13e00-b628-11ea-9454-cc4ca3ab288b.png)

Note how the `-` negative sign is rendered uglily, whereas pyplot and other backends look normal.
I believe it is internal to GR, perhaps @jheinen  could help. The relevent code I belive is [here](https://github.com/JuliaPlots/Plots.jl/blob/07146e84e5e507f24cfc7d43375425494cb8bfa4/src/backends/gr.jl#L749)

**Comment by jheinen** [comment]
I fixed the problem in 8e3f76cb.

**Comment by isentropic** [comment]
I see, wouldn't this make the ticks look unicode again? I thought [this](https://github.com/JuliaPlots/Plots.jl/blob/8e3f76cb6f929fb28a92343b61509029ab05773b/src/utils.jl#L1055) function was meant to replace unicode with normal numbers so that GR can properly render the superscripts?

**Comment by isentropic** [comment]
Or perhaps GR replaces unicode superscripts with normal superscripts internally?

**Comment by jheinen** [comment]
Hmm. I thought that would be the expected result:
<img width="712" alt="Screen Shot 2020-06-24 at 17 39 25" src="https://user-images.githubusercontent.com/5718244/85587149-cdcb3e80-b641-11ea-9688-e068af352b59.png">
Isn't it?

**Comment by isentropic** [comment]
I think the original with `convert unicode to sci` implementation is better for low res displays and users in general:
![image](https://user-images.githubusercontent.com/24591123/85589955-f9b8e500-b67e-11ea-9322-02a4a558e546.png)
because exponent font is larger and much easily read. The exponent font size approximately matches with other backends too, because most of the others rely on backends ability to draw superscripts.
This is why I believe this `convert unicode to sci` was written in the first place. However, the problem was with rendering superscripted `-` sign. Other backends like pyplot (or pgfplots):
![image](https://user-images.githubusercontent.com/24591123/85592141-de4ed980-b680-11ea-8494-90a5e3bb1f58.png)

If this can't be fixed let's leave it be. I do not think that many users are interested in negative exponents much (small numbers)

This, after all, is just a minor detail. Thank you for your great work @jheinen

**Comment by jheinen** [comment]
GR could also use its own internal LaTeX renderer, e.g. `GR.mathtex(..., ..., L"2.5\times10^{-13}")`:
<img width="140" alt="Screen Shot 2020-06-24 at 18 25 23" src="https://user-images.githubusercontent.com/5718244/85594557-5220c000-b648-11ea-9c23-efa548a72116.png">

**Comment by yha** [comment]
I was trying to find why exponents seem so tiny now on GR, and discovered it's due to 8e3f76c, which makes the exponent double superscipt (e.g. "10^{⁵}"). I think it should be reverted.
To fix the current issue, it looks like adding a space after the curly brace works around GR's odd spacing. The result looks quite nice for negative exponents, though maybe not so nice for positive ones.

Here are the results for
```
plot(plot([0,1e-10]), plot([0,1e10]), layout=(2,1))
```
When reverting 8e3f76c and adding `label = replace(label, "10^{" => "10^{ ")`:
![tmp](https://user-images.githubusercontent.com/4170948/89223107-e171a980-d5de-11ea-9e98-71dc0e20d35d.png)
and with `label = replace(label, "10^{-" => "10^{ -")` (so adding space only for negative exponents):
![tmp](https://user-images.githubusercontent.com/4170948/89223167-0108d200-d5df-11ea-8f4d-75043ab1c9a5.png)

Not sure which is better. The top one is more consistent, but also looks like too much space for positive exponents.

**Comment by isentropic** [comment]
Yeah, my concern was the same. Perhaps there is a better `-` sign? It feels like the current one is just a interword dash, not a minus. Maybe unicode longer minus would help?

**Comment by isentropic** [comment]
On top of this, why do tick marks look short on the x axis?

**Comment by jheinen** [comment]
This is, how it would look with GR's `mathtex` renderer:
<img width="668" alt="Screen Shot 2020-08-04 at 07 58 43" src="https://user-images.githubusercontent.com/5718244/89258375-57e6c980-d628-11ea-92e3-1e1477461b00.png">

Looks much better, but uses the LaTeX CM font.

There's also some extra scape after the "×" sight - this can only be fixed in GR.
```
function gr_convert_sci_tick_label(label)
    label = string("\$", convert_sci_unicode(label), "\$")
    label = string(replace(label, "×" => "\\times"))
    label
end
```

**Comment by isentropic** [comment]
Is there a latex Sans font in GR? Each tick label is already latex, if we could make those fonts Sans Serif by default that would be real nice. Pyplot has (this API) [https://matplotlib.org/3.1.1/tutorials/text/text_props.html]  (this)[https://matplotlib.org/3.1.0/gallery/text_labels_and_annotations/font_family_rc_sgskip.html] and it also comes with its internal (latex renderer)[https://matplotlib.org/3.1.1/tutorials/text/usetex.html]

**Comment by yha** [comment]
> Perhaps there is a better `-` sign? It feels like the current one is just a interword dash, not a minus. Maybe unicode longer minus would help?

Replacing all dashes with a proper minus sign (\minus, U+2212) does make things look better, and not just in the exponent. 
`convert_sci_unicode`:

![tmp](https://user-images.githubusercontent.com/4170948/89343614-34199700-d6ad-11ea-84b5-f1fd49551f9a.png)

`convert_sci_unicode` followed by `label = replace(label, "-" => "−")`:
![tmp](https://user-images.githubusercontent.com/4170948/89343464-fcaaea80-d6ac-11ea-8328-e16f71a79c95.png)

**Comment by isentropic** [comment]
I think this is much better too. Great job @yha

**Comment by isentropic** [comment]
While at this, would you please check if setting the fontfamily to Serif behaves as expected?
