### ISSUE TITLE
[BUG] xticks property does not work with pyplot backend anymore

### ISSUE THREAD

**Issue by wg030** [JuliaPlots/Plots.jl#2890]
## Note:
My issue might be related or even a duplicate of #2889 

## Details
With one of the latest updates using the pyplot backend Julia, gives the
> ERROR: LoadError: MethodError: no method matching getindex(::Int64, ::UnitRange{Int64}) 

when plotting and saving a plot that contains the xticks property:

```
using Plots

x = 0:3600:5*86400
y = x

pyplot() # commenting this out makes the code work
plt = plot( x, y, xticks=( 0:86400:5*86400, 0:5))

savefig( plt, "test.png")
```

### Versions: Julia 1.5.0 and all latest packages

**Comment by Diaga** [comment]
The index error arises because the function below expects ```latexstring``` to be enclosed by "$" sign:

https://github.com/JuliaPlots/Plots.jl/blob/c4a64351ca4e67a97a79b640d3cd0461b3cce044/src/backends/pyplot.jl#L845

This should work in your case:
```plt = plot(x, y, xticks=( 0:86400:5*86400, ["\$0\$", "\$1\$", "\$2\$", "\$3\$", "\$4\$"]))```

@BeastyBlacksmith Should we support passing iterators without elements being enclosed by "$" sign?

**Comment by benide** [comment]
I just wanted to note here what I said in #2889. as of Plots.jl 1.5.6, this requirement on tick labels with PyPlot means that the interface is different for different backends. The tick labels work as expected without "\$" delimiters with GR, for example.

**Comment by isentropic** [comment]
@Diaga  would you please see if we could first make sure that $$ are present and if they are absent optionally put them in? I thought of this case, but for some reason could failed at this (can't exactly remember why checking for surrounding $ was difficult at that time.

This is only pyplot backend behavior.  This was input for reasons mentioned in https://github.com/JuliaPlots/Plots.jl/issues/2889
Everything I did in that PR is a hack, due to matplotlib limitation really.

**Comment by isentropic** [comment]
For future cases, please mention me in any of pyplot issues. I think at this point pyplot backend is what I focused on during the last few months

**Comment by isentropic** [comment]
Perhaps @LakshyaKhatri would be interested in this issue too

**Comment by wg030** [comment]
@Diaga Thanks for the right way to do it. I have tested your solution and it works.

As far as the question of the "support of passing iterators without elements being enclosed by "$" sign? is concerned, in my humble opinion it would be pretty strange if it worked without any backend or with special backends but with other backends or maybe even only pyplot not.

**Comment by BeastyBlacksmith** [comment]
> Should we support passing iterators without elements being enclosed by "$" sign?

I don't know the specifics of the pyplot backend here, but I would expect user to pass LaTeXStrings, if they want computer modern ticklabels and get sans serif numbers if they pass plain numbers (pgfplotsx is an exeption here in that its default font is computer modern, since its actually using LaTeX)

**Comment by wg030** [comment]
> I don't know the specifics of the pyplot backend here, but I would expect user to pass LaTeXStrings, if they want computer modern ticklabels and get sans serif numbers if they pass plain numbers (pgfplotsx is an exeption here in that its default font is computer modern, since its actually using LaTeX)

If would agree that user who prefer computer modern ticklabels would pass LaTeXStrings, but I think that those users who jus pass plain numbers simply don't really care if their ticklabels are sans serif or computer modern or anything else as long as they have the correct values and don't look too ugly.

**Comment by benide** [comment]
Sorry, I just want to check since it wasn't commented on at all: Is the fact that the interface for tick labels is different now with the PyPlot backend as compared to all of the others not an issue? I would think that whatever solution is come to, using LaTeXStrings or whatever else, the first step is to make sure the interface is consistent across backends.

**Comment by vancleve** [comment]
> The index error arises because the function below expects `latexstring` to be enclosed by "$" sign:
> 
> https://github.com/JuliaPlots/Plots.jl/blob/c4a64351ca4e67a97a79b640d3cd0461b3cce044/src/backends/pyplot.jl#L845
> 
> This should work in your case:
> 
> ```julia
> plt = plot(x, y, xticks=( 0:86400:5*86400, ["\$0\$", "\$1\$", "\$2\$", "\$3\$", "\$4\$"]))
> ```

This works for single line strings, but strings with "\n" aren't interpreted correctly. For example, 
```
plot(x, y, xticks=( 0:86400:5*86400, ["\$0\n0\$", "\$1\$", "\$2\$", "\$3\$", "\$4\$"]))
```
yields
![image](https://user-images.githubusercontent.com/1442334/90698060-d14c0200-e24d-11ea-8fe0-aab8ccc8087c.png)
