### ISSUE TITLE
[BUG] plotly artifact retrieval failure

### ISSUE THREAD

**Issue by Sacha0** [JuliaPlots/Plots.jl#3071]
Please see https://github.com/JuliaLang/Pkg.jl/issues/2124 and https://github.com/JuliaPlots/Plots.jl/pull/3023#issuecomment-709528792. Best!

**Comment by fredrikekre** [comment]
Continuing from https://github.com/JuliaPlots/Plots.jl/pull/3023#issuecomment-709560853

Sure, but you can not have a `download` section in the Artifacts.toml file for non-tarball downloads.

**Comment by BeastyBlacksmith** [comment]
What would I need to put in there instead? Or just delete it ?

**Comment by fredrikekre** [comment]
Deleting it would be step one, but you will still run into the linked Pkg (or rather PackageCompiler issue) above since PackageCompiler can not install it. I wonder what the benefit is of having it as an artifact if it can't be installed at package install time? Might be easier/better to use something like a scratchspace from Scratch.jl.
