### ISSUE TITLE
Change default legend position to :outertopright

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaPlots/Plots.jl#3399]
This is halfway between a bug report and a feature request, so I'm not tagging it with either.

Please change the default legend position to :outertopright. Here's my one and only argument: a visualization package should not default to hiding part of the data you're trying to visualize.

**Comment by isentropic** [comment]
> a visualization package should not default to hiding part of the data you're trying to visualize.
well the arguably biggest plotting package matplotlib does

**Comment by niclasmattsson** [comment]
Really? I haven't used Python or matplotlib in a long time, but I thought it used a heuristic to place the legend where it doesn't overlap the data. So if Plots.jl had a similar heuristic then an inside legend would be OK, but otherwise it really should place the legend outside.

**Comment by daschw** [comment]
I agree, that it would be nicer. Maybe we could change it with the next major release. For now, you can make it your default by adding `const PLOTS_DEFAULTS = Dict{Symbol, Any}(:legend=>:outertopright)` to your `~/.julia/config/startup.jl`. You can add any plot attribute to this dict.

**Comment by isentropic** [comment]
I still think that the current implementation is good already.

It's actually `legend=:best`
'`Best`' for pyplot is actually a smart legend placement so that it does not overlap with data. 

Backends are supposed to find the best location that does not overlap with data but still manages to be within the plot. This is the best of both worlds, it is compact and does not intersect.

Some backends are unable to find the best location for the legend, hence they just fallback to `topright`

All in all, I think the current default is really good.

**Comment by isentropic** [comment]
What could be changed is the inclusion of the legend by default for single series data. If only a single series is added perhaps the default `y1` should not be placed at all

**Comment by lmiq** [comment]
I have written a simple function set the legend position in a tentative minimal-overlapping position (see https://discourse.julialang.org/t/why-plots-jl-produce-figures-looks-not-as-good-as-other-packages-even-with-pyplot/74946/30?u=leandromartinez98)

What if Plots, with a function like that, defined the 'best' position and send it to the backend, instead of expecting the backend to support that feature? Apparently pyplot is the only one having that option.

**Comment by t-bltg** [comment]
I agree that having a `:best` placement for `GR` would be an improvement, and it could be used by other backends as well.

@lmiq, can you create a `PR` ?

We'd need to `@btime ...` the placement algorithm obviously.

**Comment by lmiq** [comment]
I can try, the function which is there is already fast (on the tenths of micro seconds), and can probably be optimized still.

What would be helpful for me is just a pointer on where such a function should be implemented, within GR.

**Comment by t-bltg** [comment]
See the placeholder here:

https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/gr.jl#L1097-L1099

**Comment by lmiq** [comment]
That's perfect. As soon as possible I'll revise that function, possibly improve it l, and write a PR.

**Comment by t-bltg** [comment]
I think the function itself can reside in `src/utils.jl` and some tests can be added in `test/test_utils.jl`.

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4536.
