### ISSUE TITLE
Constant deprecation warning when using StatsPlots in Pluto notebook

### ISSUE THREAD

**Issue by mkschleg** [JuliaPlots/Plots.jl#3746]
## Details

Whenever I'm using StatsPlots in a pluto notebook I get the following warning.

```julia
┌ Warning: seriestype violin has been moved to StatsPlots.  To use: `Pkg.add("StatsPlots"); using StatsPlots`
└ @ Plots ~/.julia/packages/Plots/Awg62/src/args.jl:1206
```

To reproduce, in a pluto notebook just do:
```julia
using StatsPlots
violin(rand(20))
```

This floods the standard output on the terminal running the pluto notebook server.

Plots.jl version: 1.20.0
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client)
```

**Comment by sethaxen** [comment]
This issue came up again in https://github.com/fonsp/Pluto.jl/issues/1870. There, I said:

> The warning about `violin` moving to StatsPlots is being trigged here because this condition evaluates to `false`:
> https://github.com/JuliaPlots/Plots.jl/blob/2896c5a25a40d72c635dd60b307fe1446ec70c2f/src/args.jl#L1578

@fonsp explained that Pluto doesn't evaluate user code in Main and suggested replacing `!isdefined(Main, :StatsPlots) ` with https://github.com/fonsp/Pluto.jl/issues/1870#issuecomment-1026919276:
```julia
!haskey(
	Base.loaded_modules, 
	Base.PkgId(
		Base.UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb"), 
		"REPL"
	)
)
```

This would be an alternative (and perhaps simpler?) fix to #3357, which it seems has stalled.
