### ISSUE TITLE
[BUG] logscale label at 0 messes up labels on subsequent plots

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/Plots.jl#3781]
## Details

It makes no sense to try and have a tick label at `x=0` when `xscale=:log10`, so this may not be considered a real bug, but, once that mistake is made, labels in the plot figure don't really work anymore, even for perfectly correct plot calls. MWE:

```julia
using Plots # GR backend
plot(1:10, 1:10, xscale=:log10, xticks=([0], "can't touche me")) # silent failure
plot(1:10, 1:10) # warns GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```

The first plot fails silently (no error) and returns the plot with no labels at all:

<img width="712" alt="Screen Shot 2021-08-29 at 11 46 18 pm" src="https://user-images.githubusercontent.com/4486578/131252631-e475473e-c8f0-4efc-a596-ef27a8dca8a6.png">

The second plot should work normally but now no labels appear on the plot at all (so same as above). A warning is shown at the REPL though:
```
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```

(Note that the string tick in `xticks = ([0], "can't touche me")` seems to be required for the bug, maybe because it "forces" GR to try and place that label that can't be placed?)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

```
Plots v1.21.1
GR v0.58.1
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by t-bltg** [comment]
I'm not sure we can do something about that in `Plots.jl`, I believe this issue should be reported to https://github.com/jheinen/GR.jl.

As a side note, we can't fix all possible undefined behaviors related to undefined math ops.

**Comment by briochemc** [comment]
Pinging @jheinen : Is it worth opening an issue on GR.jl?

**Comment by jheinen** [comment]
A similar example works fine in plain GR. There's no `xticks` parameter in GR, so I can only force the behaviour by explicitly setting the X window limits. As mentioned before, trying to set `xmin=0` makes no sense when `xlog=true`. Nevertheless, `Plots` should reset the window in the second plot. This can only be changed in the `GR` backend within `Plots.jl`
```
using GR
plot(1:10, 1:10, xlog=true, xlim=(0,10))
plot(1:10, 1:10)
```

**Comment by bernd1995** [comment]
Hey. 
I also already tried to find out the reason for this issues.

The real problem seems to be in the creation of the layout int Plots, but I didn't find a way to solve it.
It seems that once this specific error is created by GR the functions padding functions like `leftpad(sp::Subplot)` in `subplots.jl` (and the ones in `layout.jl`) return `NaN`.

The weird thing that happens than (and I don't know if this is on purpose) is that subsequent plots somehow always try to update/reuse the general plot environment and all subsequent Plots will therefore look weird when it comes to padding and axes-creation.

So although I don't fully understand what is happening, what would solve the issue is creating the full plot from scratch once such an error occurred. 

I hope this helps ☺️

**Comment by t-bltg** [comment]
Was actually easy to fix once you know where to look (thanks @bernd1995 , @jheinen).
Hope the CI passes.
