### ISSUE TITLE
[FR] Add series behind

### ISSUE THREAD

**Issue by gustaphe** [JuliaPlots/Plots.jl#3834]
# Feature
A series kwarg to let you add series behind existing ones, for when execution order affects more than the drawing order.

# Motivation
Sometimes I have a main plot call, which maybe applies a recipe, sets attributes etc. Then I want to mark something with, for instance, a `hline`, but I want it behind the main series. The current way to do that is to plot the `hline` first, but this entails a couple of problems:

* In an interactive workflow it means rerunning any code that produced the main plot
* Any attributes that needs to be set in the first plot call must be moved (there's, for instance, a couple of these in `UnitfulRecipes`)
* If the `hline` is conditional, it can lead to kind of strange constructions:

```julia
plot(; attributes...)
if plot_interesting_ys
    hline!(interesting_ys)
end
plot!(x, y)
```

compared to a more natural (to me)

```julia
plot(x, y; attributes...)
if plot_interesting_ys
    hline!(interesting_ys; order=:back)
end
```

One could even consider allowing a numeric argument so you could place it at arbitrary depth, but `:front` and `:back` would cover all cases I can think of right now.

**Comment by t-bltg** [comment]
Maybe we should try to replicate `Pyplot`'s [`zorder`](https://matplotlib.org/stable/gallery/misc/zorder_demo.html).

**Comment by briederer** [comment]
Since I tried to achieve the same as is asked here I played a bit around and it seems that there is a temporary (and ugly) workaround by simply rearranging the order of the `series_list` vector of the subplot in question.
Here a quick example in case anybody needs to do this at the moment.
```julia
# Create the data and the plot with large markers and thick lines
x = rand(10)
fig = plot(x,line=2,label="line")
scatter!(fig,x,marker=10,label="marker")
title!(fig,"before")
savefig("before.png")

# reorder
fig.subplots[1].series_list = [fig.subplots[1].series_list[end]; fig.subplots[1].series_list[1:end-1]]
title!(fig,"after")
savefig("after.png")
```
**before.png:**
![before](https://user-images.githubusercontent.com/20151553/157841073-f355ae36-b0c8-4b17-9cf4-85816422755b.png)

**after.png:**
![after](https://user-images.githubusercontent.com/20151553/157841121-0096e05d-1d06-432c-bf97-febabb567902.png)

# Caveats 
However there are of course some caveats with this quick-and-dirty solution that need to be kept in mind:
 1. `fig.series_list == fig.subplots[1].series_list` is of course not `True` anymore. I don't know if this has any far-reaching consequences especially when it comes to figures with subplots. For simple plots like the one above this could be fixed by doing the same reordering also to `fig.series_list`
 2. One needs to know explicitly how many `series_list` entries are produced for the data that needs to be put into the background. If for instance one has errorbars on his data given by `yerror` the reordering from above will put only the datapoints into the background while the errorbars will still be on the same "z-order" as before. To shift datapoints with errorbars into the background one would need `fig.subplots[1].series_list = [fig.subplots[1].series_list[end-1:end]; fig.subplots[1].series_list[1:end-2]]` where both series of the data are shiftes into the background.
 3. Finally the reordering also affects the order of the legend (which is to be expected). However IMHO in most situations when something is put into the back it is also the "least-interesting thing" and therefore would be expected to be the last entry in the legend. But as I said this is minor cosmetics and especially probably a very subjective thing.
