### ISSUE TITLE
Update docs to reflect that GR is the default backend?

### ISSUE THREAD

**Issue by cbrnr** [JuliaPlots/Plots.jl#4026]
## Details
It seems like the documentation regarding the default backend(s) is outdated. The "Backend" section in the tutorial states:

> If have not previously installed any backend packages, this will plot to the browser using Plotly, or into the REPL using UnicodePlots.jl.

The [installation instructions](https://docs.juliaplots.org/latest/install/) make it seem like `GR` has to be manually installed.

However, when I `add Plots`, `GR` is automatically installed as a dependency as per the entry in `Manifest.toml`:

```
[[deps.Plots]]
deps = ["Base64", "Contour", "Dates", "Downloads", "FFMPEG", "FixedPointNumbers", "GR", "GeometryBasics", "JSON", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "Requires", "Scratch", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs", "UnicodeFun"]
git-tree-sha1 = "0d185e8c33401084cab546a756b387b15f76720c"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.23.6"
```

### Versions

Plots.jl version: v1.23.6
Output of `versioninfo()`:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by t-bltg** [comment]
PRs modifying https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/tutorial.md#plotting-backendsid-plotting-backends are welcome !

**Comment by cbrnr** [comment]
I'd be happy to submit a PR, but I wanted to check if having GR automatically installed is intentional first. May I ask why this is the case? It seems like it does pull in a number of unnecessary additional packages if the user (such as myself) never uses the GR backend.

**Comment by t-bltg** [comment]
`GR` is a hard dependency, since it's listed in the `[deps]` section of `Plots`' [`Project.toml`](https://github.com/JuliaPlots/Plots.jl/blob/1014b8f494023b93ce8a03ebaacbe9608920f5b4/Project.toml#L13).

It seems like it's the most accomplished backend from the user pov: there are some dependencies (https://github.com/jheinen/GR.jl/blob/master/Project.toml) sure, but those are either lightweight, or part of `Julia`'s stdlib (`LinearAlgebra`, `Pkg`, `Printf`, ...). I don't know the history about `GR`'s addition to `Plots.jl` though, I've only jumped recently into `Julia`'s ecosystem.

**Comment by BeastyBlacksmith** [comment]
GR is the default backend, because it is resonably fast and easy to distribute (same would hold for UnicodePlots, but that is not nearly as feature complete). We also need the compat bounds for it the most, which wouldn't be possible without it being a direct dependency.
I agree, that having an option to get Plots without GR would be nice, I currently don't see a way to do it.
