### ISSUE TITLE
`minorgrid=true` interacts with `yminorticks` inconsistently

### ISSUE THREAD

**Issue by ryofurue** [JuliaPlots/Plots.jl#4508]
When `minorgrid=true` is in force, `yminorticks=false` stops working. See the code below.

This is inconvenient because you cannot control the minor ticks with `yminorticks` alone.  I wish that the "meaning" of `minorgrid=true` were "Plot minor grid lines at minor ticks" and that `minorgrid` itself didn't affect the placement of minor ticks at all.  The present behavior can be understood if `minorgrid=true` means "Plot minor grid lines. Period."

Julia 1.8.2 (through juliaup) on macOS 12.6

````julia
using Plots

function myplot(ys; yminorticks)
  plot(ys; minorgrid=true,
       ylims=(-0.2,1.2),
       yticks = 0:0.2:1, yminorticks)
end

ys = rand(Float64, 10)
myplot(ys; yminorticks=2) # gets 1 minor tick
myplot(ys; yminorticks=1) # gets 4 minor ticks!
myplot(ys; yminorticks=false) # gets 4 minor ticks!
````

**Comment by t-bltg** [comment]
I believe that `myplot(ys; yminorticks=false) # gets 4 minor ticks!` is to be fixed.

But otherwise, the feature is documented to be the divider of the default `yminorticks`:
```julia
julia> plotattr(:Axis, :minorticks)
`minorticks` is of type Integer.

Intervals to divide the gap between major ticks into.

Axis attribute,  defaults to `false`.
```

`myplot(ys; yminorticks=1)  # 5 ÷ 1 = 5 minor ticks intervals (4 ticks)`
`myplot(ys; yminorticks=2)  # 5 ÷ 2 = 2 minor ticks intervals (1 tick)`
