### ISSUE TITLE
Map linecolor floats to color gradient

### ISSUE THREAD

**Issue by ahwillia** [JuliaPlots/Plots.jl#476]
On the `dev` branch, @tbreloff made a very nice feature:

``` julia
using Plots
labels = rand(1:2,1,10);
plot(rand(10,10), linecolor=labs, legend=false)
```

Which maps the integers to a discrete color map:

<img width="599" alt="screen shot 2016-09-08 at 2 20 16 pm" src="https://cloud.githubusercontent.com/assets/636625/18367310/663e12ee-75cf-11e6-9890-e99b110e90c9.png">

It would be really awesome to extend this to continuous color maps in the case that `labels` is an `Array` containing floats:

``` julia
using Plots
labels = randn(1,10);
plot(rand(10,10), linecolor=labs, legend=false)
```

Currently produces: 

```
ERROR: MethodError: no method matching plot_color(::Float64)
```

**Comment by tbreloff** [comment]
So there are a couple tricky issues as compared to the "integer colors":

- what gradient to use? This might be better represented using line_z so
linecolor is available to define the gradient
- is [0,1] the implied range? Or is it data-dependent?
- how to handle multiple color mappings/colorbars? (This is a general
problem to be solved... Shared colorbars among series/subplots)

Whatever the decisions this will be most easily implemented during
preprocessing before it gets into the pipeline.

**Comment by ahwillia** [comment]
> is [0,1] the implied range? Or is it data-dependent?

I would adopt the same conventions as `heatmap` and make it data-dependent.

**Comment by mkborregaard** [comment]
I'd say this is an example of a more general functionality: to apply series-level attributes such as `line_z` and `marker_z` across series or apply among-series attributes to several levels of a single series (eg `linestyle`). 

This issue is an example of the first type, as is #492, and as in that issue a workaround would be to append the lines as a single series while filling with NaN and using line_z. 

Perhaps a recipes that automatically applies these transformations could be a solution.
The recent PlotRecipes.compositeline recipe is really the basis for such a transformation for the second type.

**Comment by mkborregaard** [comment]
@daschw is it currently possible to do this using your line_z enhancements?

**Comment by daschw** [comment]
If I read the issue correctly it is (at least with GR and PyPlot):
```julia
using Plots; gr()
plot(rand(10) .+ (0.1:0.1:1)', line_z = (1:10)')
```
![gr_line_z_example](https://user-images.githubusercontent.com/16589944/32441453-0f6bb062-c2f8-11e7-8f5f-16727a69e891.png)

**Comment by mkborregaard** [comment]
Awesome, closing. @ahwillia please reopen if this was not what you were after.

**Comment by mkborregaard** [comment]
@daschw is this one of the new improvements that don't yet have an example attached to them?

**Comment by daschw** [comment]
Yes, it is.
