### ISSUE TITLE
Plotting an image into GR is flipped

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#527]
I would have a more informative title, but I don't really know how to describe how it's incorrect. I load the image using Images.jl and plot it using Plots.jl:

``` julia
img = load("MotifFigures.png")
plot(img)
```

With the PyPlot backend, I get the following picture:

![pyplotplot](https://cloud.githubusercontent.com/assets/1814174/19217517/941212fe-8d91-11e6-8d3d-fdb1e6937442.PNG)

This matches the PNG. With GR I get the following:

![grplot](https://cloud.githubusercontent.com/assets/1814174/19217521/b9428b30-8d91-11e6-9fa4-3626948c4ec0.PNG)

It looks like GR flips both axis.

**Comment by tbreloff** [comment]
This is fixed on dev:

```
julia> using Plots, TestImages

julia> img = TestImages.testimage("cameraman")
Gray Images.Image with:
  data: 512×512 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> gr(); plot(img, ratio=1)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19217607/84ed1014-8dad-11e6-92d1-79db63d61990.png)

but I'm still getting weirdness when loading the Plots reference images:

```
julia> using Images; img = load(Pkg.dir("PlotReferenceImages", "Plots/gr/0.9.4/ref1.png"))
BGRA Images.Image with:
  data: 500×300 Array{ColorTypes.BGRA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: sRGB
    spatialorder:  x y
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19217613/8c86cd92-8dad-11e6-9c53-085fdfabd77c.png)

Presumably this is due to the BGRA type??  I don't know enough about Images to know if this is a bug, or what.  @timholy do you have a quick answer?  (If not, no worries I'm sure we'll figure it out eventually)

**Comment by jheinen** [comment]
Should be fixed with https://github.com/jheinen/Plots.jl/commit/cd3ce86dbba1630f263a6ec7bc6dbb0e95e4b6a2 . Sorry for the delay ...

**Comment by jheinen** [comment]
Merged https://github.com/JuliaPlots/Plots.jl/pull/710
