### ISSUE TITLE
Don't fix now: Eventually unregister StatPlots (when 0.6 is completely out of use)

### ISSUE THREAD

**Issue by cossio** [JuliaPlots/Plots.jl#5518]
Is it possible to "unregister" `StatPlots`? Everytime I have to install the package I get confused about whether I should install `StatPlots` or `StatsPlots`.

**Comment by DilumAluthge** [comment]
Hi all, I know this issue is pretty old, but I wanted to follow-up with new developments.

So, we previously fixed this problem (the existence of both StatPlots and StatsPlots) in https://github.com/JuliaRegistries/General/pull/39292, which made StatPlots (singular) uninstallable in Julia 1.7+, which thus solved the problem of someone typing `] add StatPlots` in the REPL.

In Julia 1.14 and later, Pkg.jl will have the ability to understand that a package is deprecated. You can see the dev build of the docs here: https://pkgdocs.julialang.org/dev/registries/#Deprecated-packages (once Julia 1.14 is out, it'll be available in the regular docs build: https://pkgdocs.julialang.org/v1/registries/#Deprecated-packages)

I think we might as well take advantage of this new feature, so I've opened a PR to deprecate StatPlots (singular) in favor of StatsPlots (plural): https://github.com/JuliaRegistries/General/pull/147710
