### ISSUE TITLE
Label fontsize not changing pgfplots backend

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaPlots/Plots.jl#558]
The following command with pgfplots backend is not changing label fontsize. Same command with pyplot backend works just fine.

```scatter(Sol_U,:tof,:vinf,xlabel="Time (years)", ylabel="Arrival V(km/s)", marker = (:c, 2,stroke(0)),xlims = (6,12),tickfont=font(28),guidefont=font(28))```

where Sol_U is a dataframe.

I am using plots 0.9.4+ (master) and my Julia version is 0.5.1-pre+2

Is this a known issue ?
thanks,
Nitin

**Comment by tbreloff** [comment]
Fonts aren't handled currently by the PGFPlots backend.  In fact that backend has gotten very little love lately... contributions welcome!

**Comment by huckl3b3rry87** [comment]
Well, now I see why I was having trouble doing this....@Kristoffer might your package https://github.com/KristofferC/PGFPlotsX.jl be a better backend than PGFPlots.jl for Plots.jl?

**Comment by mkborregaard** [comment]
In my view, the best backend package is the one whose maintainer actively wants to be a good Plots backends (so I'm very open to PGFPlotsX)

**Comment by KristofferC** [comment]
What I can say, is that I believe the design of PGFPlotsX is such that it might be easier to create the Plots backend for it than for vanilla PGFPlots.jl.

If anyone feels like trying an implementation and encounters some problems I am happy to help but I will probably not do the work myself right now since I am a bit busy with other Julia stuff, and quite happy just using the PGFPlotsX API.

**Comment by daschw** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/1571
