### ISSUE TITLE
Legend position with PlotlyJS

### ISSUE THREAD

**Issue by tcovert** [JuliaPlots/Plots.jl#574]
I am not able to use the `legend` keyword to move legends using the PlotlyJS backend.  For example, this does not work:
```
julia> using Plots, Blink

julia> plotlyjs()
Plots.PlotlyJSBackend()

julia> p = plot(Plots.fakedata(50,5),w=3)

julia> plot!(p, legend = :bottom)
```
the resulting plot still has 5 legend entries, in the upper left. Is this intentional?

**Comment by tbreloff** [comment]
It's not the behavior I want, but I can't figure out how to have
independent legends in Plotly, or how to reposition it. If anyone knows how
please let me know.

**Comment by piever** [comment]
You can actually specify legend position in x and y coordinates in the layout with PlotlyJS:

```
using PlotlyJS
traces = GenericTrace[]
l = Layout(; legend = attr(x = 0., y= 0.))
for i = 1:5
    trace = scatter(; x = 1:10, y = rand(10), name = "draw $i")
    push!(traces,trace)
end
plot(traces,l)
```

Here for example x = 0, y = 0 corresponds to bottom left. I'm not sure about independent entries.

**Comment by tbreloff** [comment]
Thanks! I'll get to this eventually but a PR from someone else would speed the process. ;)

**Comment by piever** [comment]
I've implemented a simple way to get x,y position of legend from keyword (say [0,0] for bottom left, [0.5, 0] for bottom, [1,0] for bottom right), but it has a couple of issues:

1) The automated positioning of the legend with PlotlyJS is often not very good, because the cartesian axes are inside the figure and the legend will likely end up on top of them. There would need to be some method to programmatically detect a smart position (taking the axis position into account) or the user should be given the possibility of manually inputting coordinates.

<img width="641" alt="screenshot 2016-11-19 21 40 14" src="https://cloud.githubusercontent.com/assets/6333339/20458609/99d8ac76-aea1-11e6-84c3-51e815d19331.png">

2) Given that this happens via the layout, in case of several subplots all the legends are in the same position, which is determined by the position of the legend of the last subplot. This may be an inherent problem of plot.ly

<img width="622" alt="screenshot 2016-11-19 21 50 30" src="https://cloud.githubusercontent.com/assets/6333339/20458631/470c411e-aea2-11e6-9438-f4fc8ccf7cd0.png">

**Comment by kaslusimoes** [comment]
Should this be closed?

**Comment by piever** [comment]
Now you can position by inputting by hand the coordinates which works nicely. I've realized that some of the default values (say for `:bottomleft`) are not spectacular, but I'm not sure how to put it exactly above the x axis/to the right of the y axis (maybe just inputting better constant coordinates?). Anyway they're defined [here](https://github.com/JuliaPlots/Plots.jl/pull/579/files#diff-feaed6cff1b7f4ea9015afc34681e53aR96) if you wanna take a stab.

**Comment by mkborregaard** [comment]
In connection with this it'd actually be nice to let `legend` accept a tuple with the exact legend positions, also for the other backends.

**Comment by piever** [comment]
Also, I think that since Jan 18, the default legend positions for PlotlyJS kept the ridiculous values that I gave them and I'm still not sure what's a good way to set them... They are [here](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl#L99)
