### ISSUE TITLE
concise warning followed by verbose error

### ISSUE THREAD

**Issue by ggggggggg** [JuliaPlots/Plots.jl#658]
I tried to use `yscale=:log` with the `plotly` backend. This isn't supported, and there is a clear and concise warning explaining this. However, it then proceeds to throw a Domain error and fill the screen with useless information, which caused me to miss the warning the first time. It seems to me it would be more useful if only the warning were printed. I'm not sure if that is possible, but it seems worth asking for.

```
julia> plot(f,zr,yscale=:log)
WARNING: scale log is unsupported with Plots.PlotlyBackend().  Choose from: Symbol[:identity,:log10]
Error showing value of type Plots.Plot{Plots.PlotlyBackend}:
ERROR: DomainError:
 in nan_dom_err at ./math.jl:196 [inlined]
 in log10(::Float64) at ./math.jl:202
 in (::Plots.##114#115{Symbol})(::Float64) at /Users/oneilg/.julia/v0.5/Plots/src/axes.jl:148
 in optimal_ticks_and_labels(::Plots.Axis, ::Void) at /Users/oneilg/.julia/v0.5/Plots/src/axes.jl:161
 in get_ticks(::Plots.Axis) at /Users/oneilg/.julia/v0.5/Plots/src/axes.jl:204
 in tick_padding(::Plots.Axis) at /Users/oneilg/.julia/v0.5/Plots/src/backends.jl:71
 in _update_min_padding!(::Plots.Subplot{Plots.PlotlyBackend}) at 
 ...
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

**Comment by ma-laforge** [comment]
As far as I can see:

Plots.jl *did* only display a warning.  It also looks like it tried to plot anyways by simply taking `log10(zr)`.

I would presume the message that follows occurs because one of the values of `zr` is `-Inf` - because `log10(-Inf)` generates this very domain error.

My guess is that one of your frequency samples lands right on a pole... (usually slips people's mind when they include the 0Hz point).
