### ISSUE TITLE
plotlyjs colormap problem with spy

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#730]
Hi, somehow, the following very simple command does not work under plotlyjs as a backend: ```spy(eye(10), marker=(:circle,10))```. The pyplot backend displays it correctly and the gr backend also displays it with somewhat larger dots than 10 points. The plotlyjs backend doesn't display it at all and generates the error: ```ERROR: MethodError: no method matching getindex(::ColorTypes.RGBA{Float64}, ::Float64) ...``` If I specify a colormap explicitly, e.g., ```spy(eye(10), c=:viridis, marker=(:circle,10))```, then it doesn't generate error, but the displayed figure is wrong; I cannot see the expected dots (or circles). What's wrong here with plotlyjs?

**Comment by mkborregaard** [comment]
When c = :viridis shows nothing, it was because all your marker_z values were set to 1 in the spy series recipe, which causes a division by 0 here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl#L544 . This meant markers were transparent, and since markerstrokewidth = 0 for the :spy recipe, you could not see them! 

Also, that was hard to see, because the plotly backend does not produce a colorbar for marker_z, in contrast with the other backends.

I’d like to add a color bar when marker_z is set (like the other backends do) but haven’t gotten it to work. I have tried adding the code 
```julia
            d_out[:colorscale] = plotly_colorscale(series[:markercolor], series[:markeralpha])
            d_out[:showscale] = true

```
to line 546 but it does not have the expected effect.
