### ISSUE TITLE
No API documentation

### ISSUE THREAD

**Issue by Jackels** [JuliaPlots/Plots.jl#744]
I want to know what the signature is for Plots.scatter
Searching on your website yields this
![useless search](https://cloud.githubusercontent.com/assets/5102951/24250454/427cd046-0fd7-11e7-825d-c9b4cf5b8b77.png)

Which is not helpful
going into your source is equally unhelpful
```
help?> Plots.scatter
  No documentation found.

  Plots.scatter is a Function.

  # 1 method for generic function "scatter":
  scatter(args...; kw...) at ~\.julia\v0.5\Plots\src\Plots.jl:139
```
Going into that file it looks like this
```
# define and export shorthand plotting method definitions
macro shorthands(funcname::Symbol)
    funcname2 = Symbol(funcname, "!")
    esc(quote
        export $funcname, $funcname2
        $funcname(args...; kw...) = plot(args...; kw..., seriestype = $(quot(funcname)))
        $funcname2(args...; kw...) = plot!(args...; kw..., seriestype = $(quot(funcname)))
    end)
end

@shorthands scatter
@shorthands bar
@shorthands barh
@shorthands histogram
```

What am I supposed to do now?
What are the inputs for your function?
Where is your documentation?

**Comment by joshday** [comment]
Essentially `scatter(args...; kw...) = plot(args...; kw..., seriestype = :scatter)`

The arguments and keyword arguments can be a wide variety of things.  Please spend some time reading the documentation from the beginning to get a better idea of how Plots works: https://juliaplots.github.io. 

I don't think you would have this question if you read the documentation.  On a highly-watched repo like Plots, issues ping a lot of people, so please be respectful of that.

**Comment by Jackels** [comment]
I am used to documentations that look like this
http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.scatter
There is a clear interface, the input is described.
I am not able to find anything like this for Plots.scatter.

**Comment by mkborregaard** [comment]
As @joshday says, everything in Plots is done by calls to `plot`. `scatter` is just a shorthand for convenience, which calls `plot` with that seriestype. So use the documentation to understand `plot`, and all else will come. Here is the short version: `plot` takes x, y and optionally z values as positional arguments. Everything else is done with keyword arguments (in Plots lingo called attributes). A list of all the keyword arguments to Plots is found here: https://juliaplots.github.io/attributes/ , and in the console you can use the `plotattr` function to explore keywords and their meaning.
You are used to documentation that looks like that for matplotlib (I assume you come from Python), but in fact much of Julia's documentation uses a different format. That is because multiple dispatch allows for a much greater variety of function signatures. Spend a little time getting accustomed to julia documentation and I'm sure you'll appreciate it.
