### ISSUE TITLE
make savefig(..., "filename.svg") save self-contained SVG for plotlyjs

### ISSUE THREAD

**Issue by tpapp** [JuliaPlots/Plots.jl#750]
MWE:
```julia
using Plots; plotlyjs()
savefig(plot(rand(100)), "/tmp/plot.svg")
```
produces a HTML file which calls Javascript to produce the SVG.

However,
```julia
plt = plot(rand(100))
PlotlyJS.savefig(plt.o, "/tmp/plot.svg")
```
produces an SVG. (workaround suggested by @piever on Gitter). It would be great if `Plots.savefig` and `Plots.svg` would do this instead.

**Comment by piever** [comment]
I thought I'd make a PR: the issue is [here](https://github.com/JuliaPlots/Plots.jl/blob/155587628076c68e1601aea0667354daa50f7f1d/src/backends/plotlyjs.jl#L88) and it'd be fixed if the `show` function was defined for svg as it is defined for the other formats (using the PlotlyJS method). Problem is, displaying plots in Jupyter notebook also calls `_show` with svg format, so if I change it there, the Jupyter plots go from being interactive to just displaying a static svg. I'm not sure what's the cleanest way of solving this and I couldn't figure out exactly what happens when you display in IJulia and why it calls `_show` with svg format whereas plotting in Electron doesn't.

**Comment by mkborregaard** [comment]
Have you tested that interactivity is lost in IJulia if you change the code? I don't think we'd want to lost that.

**Comment by tpapp** [comment]
Would the following upgrade path work:
1. introduce another function or method which Jupyter can use, eg `svg_dynamic`,
2. Make a fix for Jupyter to use that, let it trickle through,
3. in the meantime, define a `show` method for `MIME("image/svg")` that can be used as a workaround,
4. once the changes go through Jupyter, replace `svg` with the static version?

**Comment by piever** [comment]
Found a cleaner solution: added a method to show html for PlotlyJS, so that now it doesn't resort to the svg method for plotting in IJulia. I've changed the svg to use PlotlyJS. I've also slightly changed the display in IJulia and it seems to resolve the flickering I add when using Interact. I'll add a PR right now.
