### ISSUE TITLE
series_annotations in bar plots in unusual positions for gr and pyplot backends

### ISSUE THREAD

**Issue by JobJob** [JuliaPlots/Plots.jl#761]
Making a bar plot and trying to get labels on the top of each bar using `series_annotations`:
```
using Plots
gr()
# pyplot()
# plotly()
data = 1:3
labels = string.(data)
bar(data; series_annotations=labels, ylims=(0,5)) 
```
This works well with the Plotly backend, the labels go at the middle of the top of each bar.

With the GR and PyPlot backends the labels go in funny places

Plotly:
![plotly bar](https://cloud.githubusercontent.com/assets/854183/24825295/19ee2a00-1c5f-11e7-8ad0-e5e7d5a9986e.png)

PyPlot:
<img width="679" alt="pyplot bar" src="https://cloud.githubusercontent.com/assets/854183/24825312/89d9a222-1c5f-11e7-8620-22c9f82976c8.png">

GR:
<img width="679" alt="gr bar" src="https://cloud.githubusercontent.com/assets/854183/24825300/284a4b60-1c5f-11e7-9bc9-392e25c71176.png">

Anyway clearly this package rocks in that I can just try another backend with a one line change and it works or looks better or is faster etc.

Cheers.

**Comment by mkborregaard** [comment]
This is because `bar` for gr and pyplot is handled by the recipe here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L325-L378 , which draws the bars as shapes and thus changes the x and y values. For plotly the native bar implementation is used.

There could be two solutions:
1. to revert gr and pyplot to use the native bar implementation
2. perhaps to have the bar recipe create the bars in a second series with the `@series` macro, and return an invisible point series with the original x and y values?

**Comment by stugorf** [comment]
Has there been a solution developed for pyplot backend rendering of bar charts with series_annotations?

**Comment by mkborregaard** [comment]
no, unfortunately not. The best approach is to add a new series without markers with the same data, then then apply series_annotations to that.

**Comment by stugorf** [comment]
Thank you, I’ll try that!

Regards,

-David
________________________________

**Comment by clad26** [comment]
Any progress on this?
As of Julia 1.6, it seems to me that ``` series_annotations ``` is completely broken, at least with GR

**Comment by clad26** [comment]
> no, unfortunately not. The best approach is to add a new series without markers with the same data, then then apply series_annotations to that.

I'm sorry, I didn't get that... can you please elaborate?
