### ISSUE TITLE
Histograms have the wrong number of bins

### ISSUE THREAD

**Issue by ttparker** [JuliaPlots/Plots.jl#898]
The documentation says of the `bins` option, "For histogram-types, defines the number of bins, or the edges, of the histogram."  But `histogram` usually doesn't use the correct number of bins specified with this option.  I tried `histogram(rand(1000), bins = n)` for n = 1 through 50, and found that it only output the correct number of bins for n = 1, 2, 5, 10, 20, or 50.  For any other value of n, it displays a histogram whose number of bins was in that list, somewhere near the number set using `bins`.

**Comment by mkborregaard** [comment]
Yes, this is intentional, the histogram implementation (which is in StatsBase) adjusts the bin numbers to give breaks that align with ticks (e.g. integer breaks). This makes it easier to interpret the bin values (and is a common convention, it's done by all statistics packages I know of). You can get complete control of bins by passing a Vector instead, e.g. `bins = linspace(extrema(x)..., 25)`.
This may not have been clear enough from the docstring, so I've suggested a change: https://github.com/JuliaPlots/Plots.jl/pull/900 You're very welcome to comment on the phrasing there.
