### ISSUE TITLE
Multiple labels must be in a row vector

### ISSUE THREAD

**Issue by dalum** [JuliaPlots/Plots.jl#901]
When plotting with labels put in a column vector or tuple, the labels are printed as "trace 0", "trace 1", and so forth. A MWE to reproduce this is:
```julia
using Plots
plotly()
xs = 1:10
f(x) = [0, 1x, 2x]
plot(xs, hcat(map(f, xs)...)', labels=["Total", "Channel 1", "Channel 2"])
```
For someone unfamiliar with Plots (me), this behaviour is quite unexpected—and as far is I can tell, undocumented. I think it would be nice if `plot` would accept labels in any sequence type, not just row vectors.

**Comment by mkborregaard** [comment]
The solution is to become familiar with Plots :-) The basic premise of Plots input is that Vectors input values for each value in a series, RowVectors input values for each series in a plot. It is thoroughly documented (https://juliaplots.github.io/input_data/), and once you realize this, Plots calls are fairly easy to get to make sense.

**Comment by eveydee** [comment]
Okay. I understand the rationale now and it makes sense, even if it is in the reverse order of how I think about my data. Just have to rotate everything by 90 degrees in my head. :-)

I think it would be nice to have an example below, to illustrate this behaviour for both `markersize` and `label`.

**Comment by mkborregaard** [comment]
It's definitely important to have this documented well, and open to consider any suggestion for this. If you're up for it, you could try to suggest a change in a PR against PlotDocs?

**Comment by eveydee** [comment]
I'll have a look at it tomorrow.

**Comment by tpapp** [comment]
Perhaps print an informative warning/error for `labels::Vector`?

**Comment by asprionj** [comment]
I do see that becoming familiar with Plots helps figuring out such unnecessarily strict behaviour quicker. Especially since it does not produce a warning or error, it just does something else (like displaying standard labels).

But I still don't see why this is necessary at all. When I get a Vector or a Nx1 matrix of labels out of some function, package, etc. which I cannot (or don't want to) change, why I have to do such an ugly hack like `label = permutedims(signal_names[:,:])` if it's a `Vector`? There is no ambiguity if I plot 3 signals and specify 3 labels, irrespective of the orientation or dimensionality of the "container" for the 3 labels...
