### ISSUE TITLE
plotting in GR prints "best"

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#924]
I am seeing "best"printed out (both in IJulia notebook, and the REPL) whenever plotting with the default backend.

```julia
julia> using Plots

julia> Pkg.installed("Plots")
v"0.11.3"

julia> backend()
Plots.GRBackend()

julia> plot(rand(2,), rand(2,))
best

julia> plotly()
Plots.PlotlyBackend()

julia> plot(rand(2,), rand(2,))

julia> 
```

This wouldn't bother me, except that I'm using `Interact.jl` in the notebook, and the "best"s accumulate. Sorry if this issue belongs in https://github.com/jheinen/GR.jl or https://github.com/JuliaPlots/PlotsGR.jl .

also:
```
julia> Pkg.installed("GR")
v"0.20.0"

julia> Pkg.installed("PlotsGR")
ERROR: PlotsGR is not a package (not registered or installed)
```

**Comment by daschw** [comment]
This is because of [this line](https://github.com/JuliaPlots/Plots.jl/blob/v0.11.3/src/backends/gr.jl#L451) in gr.jl in the Plots v0.11.3 release. It has been fixed on master by https://github.com/JuliaPlots/Plots.jl/pull/910. However, everyone using julia v0.5 is stuck with Plots v0.11.3 so maybe we should include @jheinen 's fix there.

**Comment by juliohm** [comment]
Same issue here. Good to know it is fixed in master. Looking forward to move to Julia v0.6.

**Comment by mkborregaard** [comment]
Alright I tagged a new 0.5-only release to fix this
